pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        IMAGE_NAME = "infrawave/my-app"
        GIT_USER   = "Rushi6402"
        GIT_EMAIL  = "rushipatil8582@gmail.com"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('whoiam') {
            steps {
                sh 'whoami'
            }
        }

        stage('Build and Push Image') {
            when { branch 'master' }
            steps {
                script {
                    env.IMAGE_TAG = "build-${BUILD_NUMBER}"

                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f "Main Branch Code/Dockerfile" "Main Branch Code/"
                           """
                        sh ''' echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin '''

                         sh """   docker push ${IMAGE_NAME}:${IMAGE_TAG}
                             """
                    }
                }
            }
        }
    }
}
