pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        IMAGE_NAME = "infrawave/my-app"
        GIT_USER   = "Rushi6402"
        GIT_EMAIL  = "rushipatil6402@gmail.com"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
       stage('SonarCloud Analysis') {
           steps {
              withCredentials([usernamePassword(
                  credentialsId: 'sonar-token',
                  usernameVariable: 'SONAR_USER',
                  passwordVariable: 'SONAR_TOKEN'
              )]) {
              	  sh '''
                      cd "Main Branch Code"
                      pip install pysonar --break-system-packages
                      pysonar \
                        --sonar-token=$SONAR_TOKEN \
                        --sonar-project-key=K8s-GitOps \
                        --sonar-organization=rushi6402
                  '''
               }
           }
       }

       stage('Build and Push Image') {
            when { branch 'master' }
            steps {
                script {
                    env.IMAGE_TAG = "build-${BUILD_NUMBER}"

                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f "Main Branch Code/Dockerfile" "Main Branch Code/"
                           """
                        sh ''' echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin '''

                         sh """   docker push ${IMAGE_NAME}:${IMAGE_TAG}
                             """
                    }
                }
            }
        }
        stage('Update K8s Manifest') {
            when { branch 'master' }
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )]) {
                        sh """
                        set -e
                        git config user.name "$GIT_USER"
                        git config user.email "$GIT_EMAIL"

                        git fetch origin
                        git checkout master
                        git reset --hard origin/master

                        sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" "Main Branch Code/k8s/deployment.yml"

                        git add "Main Branch Code/k8s/deployment.yml"
                        git diff --cached --quiet || git commit -m "Updated image to ${IMAGE_TAG}"
                        git push https://\${GIT_USERNAME}:\${GIT_TOKEN}@github.com/Rushi6402/K8s-GitOps.git master
                        """
                    }
                }
            }
        }
    }
}
