pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        IMAGE_NAME = "infrawave/my-app"
        GIT_USER   = "Rushi6402"
        GIT_EMAIL  = "rushipatil6402@gmail.com"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('SonarCloud Analysis') {
            steps {
                withCredentials([string(
                    credentialsId: 'sonar-token',
                    variable: 'SONAR_TOKEN'
                )]) {
                   sh '''
                       docker run --rm \
                         -e SONAR_TOKEN=$SONAR_TOKEN \
                         -v $(pwd):/usr/src \
                         sonarsource/sonar-scanner-cli \
                         -Dsonar.projectKey=K8s-GitOps \
                         -Dsonar.organization=rushi6402 \
                         -Dsonar.sources=. \
                         -Dsonar.host.url=https://sonarcloud.io
                   '''
                }
            }
       }

       stage('Build and Push Image') {
            when { branch 'master' }
            steps {
                script {
                    env.IMAGE_TAG = "build-${BUILD_NUMBER}"

                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f "Main Branch Code/Dockerfile" "Main Branch Code/"
                           """
                        sh ''' echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin '''

                         sh """   docker push ${IMAGE_NAME}:${IMAGE_TAG}
                             """
                    }
                }
            }
        }
        stage('Trivy Security Scan') {
            sh """
                trivy image \
                  --exit-code 1 \
                  --severity CRITICAL \
                  --no-progress \
                  ${IMAGE_NAME}:${IMAGE_TAG}
            """
        }
        stage('Update K8s Manifest') {
            when { branch 'master' }
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    )]) {
                        sh """
                        set -e
                        git config user.name "$GIT_USER"
                        git config user.email "$GIT_EMAIL"

                        git fetch origin
                        git checkout master
                        git reset --hard origin/master

                        sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" "Main Branch Code/k8s/deployment.yml"

                        git add "Main Branch Code/k8s/deployment.yml"
                        git diff --cached --quiet || git commit -m "Updated image to ${IMAGE_TAG}"
                        git push https://\${GIT_USERNAME}:\${GIT_TOKEN}@github.com/Rushi6402/K8s-GitOps.git master
                        """
                    }
                }
            }
        }
    }
}
